/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Feed;

import control.App;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import model.Post;
import model.User;
import view.SearchSolicitationBlock.UserGroups;

/**
 *
 * @author Usuario
 */
public class FeedView extends javax.swing.JPanel {

    
    private PostView p1;
    private User user;
    
    public FeedView() {
        GridBagLayout layout = new GridBagLayout(); 
        initComponents();
        this.user = App.getNetwork().getCurrentUser();
        postP.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        
        int i = 0;
        for(Post post: this.user.getFeed()){
            p1 = new PostView(App.getNetwork().getCurrentUser(), post);
            c.insets = new Insets(0, 0, 10, 10);
            c.gridx = 0;
            c.gridy = i;
            postP.add(p1, c);
            i++;      
        }   
    }
    public FeedView(User user) {
        initComponents();
        this.user = user;
        
        GridBagLayout layout = new GridBagLayout(); 
        postP.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        PostView p1;
            
        int i = 0;
        for(Post post:user.getFeed()){
            p1 = new PostView(user, post);
            c.insets = new Insets(0, 0, 10, 10);
            c.gridx = 0;
            c.gridy = i;
            postP.add(p1, c);
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPost = new javax.swing.JButton();
        postP = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 51, 255));

        newPost.setText("Nova Postagem");
        newPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout postPLayout = new javax.swing.GroupLayout(postP);
        postP.setLayout(postPLayout);
        postPLayout.setHorizontalGroup(
            postPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        postPLayout.setVerticalGroup(
            postPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(newPost)
                .addContainerGap())
            .addComponent(postP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newPost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPostActionPerformed
        if(this.user == App.getNetwork().getCurrentUser()){
            App.showNewPost();
        }else{
            App.showNewPost(user);
        }
        
    }//GEN-LAST:event_newPostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newPost;
    private javax.swing.JPanel postP;
    // End of variables declaration//GEN-END:variables
}
