/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Feed;

import control.App;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import model.User;

/**
 *
 * @author Usuario
 */
public class FeedView extends javax.swing.JPanel {

    /**
     * Creates new form FeedView
     */
    public FeedView() {
        GridBagLayout layout = new GridBagLayout(); 
        initComponents();
        post.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        
        //int p = App.getNetwork().user.getFeed().size();
        for(int i=0; i<10; i++){
            PostView p1 = new PostView();    
            c.insets = new Insets(0, 0, 10, 0);
            c.gridx = 0;
            c.gridy = i;
            post.add(p1, c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPost = new javax.swing.JButton();
        post = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 51, 255));

        newPost.setText("Nova Postagem");
        newPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout postLayout = new javax.swing.GroupLayout(post);
        post.setLayout(postLayout);
        postLayout.setHorizontalGroup(
            postLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        postLayout.setVerticalGroup(
            postLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(newPost)
                .addContainerGap())
            .addComponent(post, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newPost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPostActionPerformed
        App.ShowNewPost();
    }//GEN-LAST:event_newPostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newPost;
    private javax.swing.JPanel post;
    // End of variables declaration//GEN-END:variables
}
